"""
Tests for ExtractionPipeline, WikipediaConnector, and ArchiveOrgConnector.

Includes:
  - Property 21: Raw document preservation
  - Property 22: Attribution metadata completeness
  - Property 23: Incremental deduplication (no duplicates past checkpoint)
  - Unit tests for connector error handling
  - Unit tests for ExtractionPipeline.run()
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from unittest.mock import MagicMock, patch

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from psychohistory.connectors.base import SearchQuery
from psychohistory.connectors.wikipedia import WikipediaConnector
from psychohistory.connectors.archiveorg import ArchiveOrgConnector
from psychohistory.event_ingester import EventIngester
from psychohistory.extraction_pipeline import ExtractionPipeline, ExtractionReport
from psychohistory.models import RawSourceDocument


# ---------------------------------------------------------------------------
# Helpers / factories
# ---------------------------------------------------------------------------


def _make_raw_doc(
    raw_content: str = "In 1789 the French Revolution began.",
    connector_name: str = "test_connector",
    source_url: str = "https://example.com/doc",
    extraction_timestamp: datetime | None = None,
) -> RawSourceDocument:
    return RawSourceDocument(
        id=str(uuid.uuid4()),
        source_url=source_url,
        connector_name=connector_name,
        raw_content=raw_content,
        content_type="text/plain",
        extraction_timestamp=extraction_timestamp or datetime.now(timezone.utc),
        metadata={},
    )


def _make_mock_connector(
    connector_name: str = "mock_connector",
    docs: list[RawSourceDocument] | None = None,
) -> MagicMock:
    connector = MagicMock()
    connector.connector_name = connector_name
    connector.search.return_value = docs or []
    return connector


# ---------------------------------------------------------------------------
# Property 21: Raw document preservation
# **Validates: Requirements 10.3**
# ---------------------------------------------------------------------------


@given(raw_content=st.text(min_size=1, max_size=200))
@settings(max_examples=50)
def test_raw_document_preserved(raw_content: str) -> None:
    """
    **Validates: Requirements 10.3**

    Property 21: The RawSourceDocument stored must have raw_content identical
    to the original content.
    """
    doc = _make_raw_doc(raw_content=raw_content)
    # The raw_content must be preserved exactly as provided
    assert doc.raw_content == raw_content


# ---------------------------------------------------------------------------
# Property 22: Attribution metadata completeness
# **Validates: Requirements 10.4, 10.6**
# ---------------------------------------------------------------------------


@given(
    raw_content=st.text(min_size=10, max_size=200).filter(
        lambda s: any(c.isdigit() for c in s)
    ),
    connector_name=st.text(min_size=1, max_size=50, alphabet=st.characters(whitelist_categories=("Lu", "Ll", "Nd"), whitelist_characters="_-")),
    source_url=st.just("https://example.com/article"),
)
@settings(max_examples=50)
def test_attribution_metadata_complete(
    raw_content: str, connector_name: str, source_url: str
) -> None:
    """
    **Validates: Requirements 10.4, 10.6**

    Property 22: For any HistoricalEvent generated by the ExtractionPipeline,
    source_url, connector_name, and extraction_timestamp must be non-null.
    """
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    # Build a doc with a year in the content to ensure transformation succeeds
    content_with_year = raw_content
    if not any(str(y) in raw_content for y in range(1000, 2025)):
        content_with_year = f"In 1900 {raw_content}"

    doc = RawSourceDocument(
        id=str(uuid.uuid4()),
        source_url=source_url,
        connector_name=connector_name,
        raw_content=content_with_year,
        content_type="text/plain",
        extraction_timestamp=datetime.now(timezone.utc),
        metadata={},
    )

    events = pipeline._transform(doc)
    for event in events:
        assert event.source_url is not None, "source_url must not be None"
        assert event.connector_name is not None, "connector_name must not be None"
        assert event.extraction_timestamp is not None, "extraction_timestamp must not be None"


# ---------------------------------------------------------------------------
# Property 23: Incremental deduplication
# **Validates: Requirements 10.11**
# ---------------------------------------------------------------------------


def test_incremental_extraction_no_duplicates() -> None:
    """
    **Validates: Requirements 10.11**

    Property 23: Documents with extraction_timestamp before the checkpoint
    must not be ingested.
    """
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    checkpoint_time = datetime(2023, 6, 1, tzinfo=timezone.utc)
    connector_name = "test_connector"

    # Set checkpoint
    pipeline._last_extraction[connector_name] = checkpoint_time

    # Document BEFORE checkpoint — should be excluded
    old_doc = _make_raw_doc(
        raw_content="In 1789 the French Revolution began.",
        connector_name=connector_name,
        extraction_timestamp=datetime(2023, 1, 1, tzinfo=timezone.utc),
    )

    # Document AFTER checkpoint — should be included
    new_doc = _make_raw_doc(
        raw_content="In 1815 the Battle of Waterloo ended the Napoleonic Wars.",
        connector_name=connector_name,
        extraction_timestamp=datetime(2023, 12, 1, tzinfo=timezone.utc),
    )

    assert not pipeline._is_incremental_eligible(old_doc, connector_name), (
        "Old document should not be eligible"
    )
    assert pipeline._is_incremental_eligible(new_doc, connector_name), (
        "New document should be eligible"
    )


def test_incremental_no_checkpoint_always_eligible() -> None:
    """Without a checkpoint, all documents are eligible."""
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    doc = _make_raw_doc(
        extraction_timestamp=datetime(2000, 1, 1, tzinfo=timezone.utc),
    )
    assert pipeline._is_incremental_eligible(doc, "any_connector")


# ---------------------------------------------------------------------------
# Wikipedia connector: returns empty on network error
# ---------------------------------------------------------------------------


def test_wikipedia_connector_returns_empty_on_network_error() -> None:
    """WikipediaConnector.search() returns [] when requests raises a timeout."""
    connector = WikipediaConnector()
    query = SearchQuery(text="French Revolution")

    with patch("psychohistory.connectors.wikipedia._get_requests") as mock_get_req:
        import requests as req_module
        mock_requests = MagicMock()
        mock_requests.get.side_effect = req_module.exceptions.Timeout("timed out")
        mock_get_req.return_value = mock_requests

        result = connector.search(query)

    assert result == [], "Should return empty list on timeout"


def test_wikipedia_connector_returns_empty_when_not_installed() -> None:
    """WikipediaConnector.search() returns [] when requests is not installed."""
    connector = WikipediaConnector()
    query = SearchQuery(text="test")

    with patch("psychohistory.connectors.wikipedia._get_requests", return_value=None):
        result = connector.search(query)

    assert result == [], "Should return empty list when requests not installed"


# ---------------------------------------------------------------------------
# ArchiveOrg connector: returns empty when not installed
# ---------------------------------------------------------------------------


def test_archiveorg_connector_returns_empty_when_not_installed() -> None:
    """ArchiveOrgConnector.search() returns [] when internetarchive is not installed."""
    connector = ArchiveOrgConnector()
    query = SearchQuery(text="history")

    with patch(
        "psychohistory.connectors.archiveorg._get_internetarchive", return_value=None
    ):
        result = connector.search(query)

    assert result == [], "Should return empty list when internetarchive not installed"


def test_archiveorg_connector_returns_empty_on_error() -> None:
    """ArchiveOrgConnector.search() returns [] when the library raises an exception."""
    connector = ArchiveOrgConnector()
    query = SearchQuery(collection="americana")

    with patch("psychohistory.connectors.archiveorg._get_internetarchive") as mock_ia:
        mock_ia_module = MagicMock()
        mock_ia_module.search_items.side_effect = ConnectionError("network error")
        mock_ia.return_value = mock_ia_module

        result = connector.search(query)

    assert result == [], "Should return empty list on connection error"


# ---------------------------------------------------------------------------
# ExtractionPipeline.run() — basic integration
# ---------------------------------------------------------------------------


def test_extraction_pipeline_run_returns_report() -> None:
    """ExtractionPipeline.run() returns a valid ExtractionReport."""
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    docs = [
        _make_raw_doc(
            raw_content="In 1789 the French Revolution began in Paris.",
            source_url="https://example.com/french-revolution",
        ),
        _make_raw_doc(
            raw_content="In 1815 the Battle of Waterloo ended the Napoleonic Wars.",
            source_url="https://example.com/waterloo",
        ),
    ]
    connector = _make_mock_connector(docs=docs)

    query = SearchQuery(text="history")
    report = pipeline.run(connector, query)

    assert isinstance(report, ExtractionReport)
    assert report.connector_name == "mock_connector"
    assert report.documents_retrieved == 2
    assert report.events_generated >= 0
    assert isinstance(report.executed_at, datetime)


def test_extraction_pipeline_discards_documents_without_required_fields() -> None:
    """Documents without a year in content are discarded."""
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    # Document with no year — should be discarded
    docs = [
        _make_raw_doc(
            raw_content="No date information here at all.",
            source_url="https://example.com/no-date",
        ),
    ]
    connector = _make_mock_connector(docs=docs)

    query = SearchQuery(text="test")
    report = pipeline.run(connector, query)

    assert report.documents_discarded >= 1
    assert report.events_generated == 0


def test_extraction_pipeline_run_updates_checkpoint() -> None:
    """After run(), the checkpoint for the connector is updated."""
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    connector = _make_mock_connector(connector_name="wiki", docs=[])
    query = SearchQuery(text="test")

    assert "wiki" not in pipeline._last_extraction

    pipeline.run(connector, query)

    assert "wiki" in pipeline._last_extraction
    assert isinstance(pipeline._last_extraction["wiki"], datetime)


def test_extraction_pipeline_deduplicates_within_batch() -> None:
    """Duplicate documents in the same batch produce only one event."""
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    # Two identical documents
    content = "In 1789 the French Revolution began."
    docs = [
        _make_raw_doc(raw_content=content, source_url="https://example.com/a"),
        _make_raw_doc(raw_content=content, source_url="https://example.com/b"),
    ]
    connector = _make_mock_connector(docs=docs)

    query = SearchQuery(text="test")
    report = pipeline.run(connector, query)

    # Both docs retrieved, but only 1 unique event
    assert report.documents_retrieved == 2
    assert report.events_generated == 1


def test_extraction_pipeline_transform_extracts_year() -> None:
    """_transform() correctly extracts a year from content."""
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    doc = _make_raw_doc(raw_content="In 1945 World War II ended.")
    events = pipeline._transform(doc)

    assert len(events) == 1
    assert events[0].date.year == 1945


def test_extraction_pipeline_transform_returns_empty_without_year() -> None:
    """_transform() returns [] when no year can be extracted."""
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    doc = _make_raw_doc(raw_content="No year information here.")
    events = pipeline._transform(doc)

    assert events == []


def test_extraction_pipeline_transform_sets_attribution_metadata() -> None:
    """_transform() sets source_url, connector_name, extraction_timestamp."""
    ingester = EventIngester()
    pipeline = ExtractionPipeline(event_ingester=ingester)

    ts = datetime(2023, 6, 15, tzinfo=timezone.utc)
    doc = _make_raw_doc(
        raw_content="In 1789 the French Revolution began.",
        connector_name="wikipedia",
        source_url="https://en.wikipedia.org/wiki/French_Revolution",
        extraction_timestamp=ts,
    )
    events = pipeline._transform(doc)

    assert len(events) == 1
    event = events[0]
    assert event.source_url == "https://en.wikipedia.org/wiki/French_Revolution"
    assert event.connector_name == "wikipedia"
    assert event.extraction_timestamp == ts
